const moviesData = [
  {
    id: 1,
    title: "Inception",
    releaseYear: 2010,
    genre: "Sci-Fi",
    tagline: "Your mind is the scene of the crime.",
    imageUrl: "https://fr.web.img2.acsta.net/medias/nmedia/18/72/34/14/19476654.jpg",
  },
  {
    id: 2,
    title: "Interstellar",
    releaseYear: 2014,
    genre: "Sci-Fi",
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    imageUrl: "https://fr.web.img3.acsta.net/pictures/14/09/24/12/08/158828.jpg",
  },
  {
    id: 3,
    title: "The Homelander",
    releaseYear: 2008,
    genre: "Action",
    tagline: "Why So Serious?",
    imageUrl: "https://www.humanite.fr/wp-content/uploads/2023/12/theboys2-p28-12_HS5.jpg",
  },
  {
    id: 4,
    title: "The Dark Knight",
    releaseYear: 2008,
    genre: "Action",
    tagline: "Why So Serious?",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/8/83/Dark_knight_rises_poster.jpg",
  },
  {
    id: 5,
    title: "Ford vs Ferrari",
    releaseYear: 2006,
    genre: "Sport",
    tagline: "Fast cars",
    imageUrl: "https://m.media-amazon.com/images/S/pv-target-images/b7a51fcdee29dcb53bc11170b510e85ae808176477d01a00795ad7288d69f5ac.jpg",
  },
  {
    id: 6,
    title: "A Man Called Otto",
    releaseYear: 2022,
    genre: "Drama",
    tagline: "Nice people",
    imageUrl: "https://images.justwatch.com/poster/303378875/s332/a-man-called-otto",
  },
  // Adding new movies below
  {
    id: 7,
    title: "Parasite",
    releaseYear: 2019,
    genre: "Thriller",
    tagline: "Act like you own the place.",
    imageUrl: "https://japoncinema.com/wp-content/uploads/2020/03/81n5eExCJLL._AC_SL1500_.jpg",
  },
  {
    id: 8,
    title: "La La Land",
    releaseYear: 2016,
    genre: "Musical",
    tagline: "Here's to the fools who dream.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/a/ab/La_La_Land_%28film%29.png",
  },
  {
    id: 9,
    title: "Joker",
    releaseYear: 2019,
    genre: "Drama",
    tagline: "Put on a happy face.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg",
  },
  {
    id: 10,
    title: "Mad Max: Fury Road",
    releaseYear: 2015,
    genre: "Action",
    tagline: "What a Lovely Day.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/6/6e/Mad_Max_Fury_Road.jpg",
  },
  // Add more movies as needed
];

  export default  moviesData;